"""
Django settings for emarket project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-0w2(yk75b*$i33cfqb5+0@f3k-605^+&a%sc*w)$=j7c(&$$6q"

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True

ALLOWED_HOSTS = ["52.232.22.140" ,"127.0.0.1", "api.3sfragrance.com", "localhost"]


LANGUAGE_CODE = "en"
USE_I18N = True

OPAY_MERCHANT_ID = "281825082914353"
OPAY_PUBLIC_KEY = "OPAYPUB17564744895120.9517191837351693"
OPAY_SECRET_KEY = "OPAYPRV17564744895120.37102856115071037"
OPAY_ENV = "production"

FRONTEND_URL = "https://www.3sfragrance.com"
BACKEND_URL = "https://api.3sfragrance.com"
# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "rest_framework_simplejwt",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "product.apps.ProductConfig",
    "account.apps.AccountConfig",
    "order.apps.OrderConfig",
    "cart.apps.CartConfig",
    "contact.apps.ContactConfig",
    "payment.apps.PaymentConfig",
    "django_filters",
    "corsheaders",
    "rest_framework_simplejwt.token_blacklist",
]

JAZZMIN_SETTINGS = {
    "site_title": "Shop Dashboard",
    "site_brand": "Future",
    "welcome_sign": "Welcome to Dashboard",
    "site_logo": "images/logo.png",
    "show_sidebar": True,
    "navigation_expanded": True,
    "topmenu_links": [
        {"name": "Home  ", "url": "/", "permissions": ["auth.view_user"]},
    ],
    "icons": {
        "auth.user": "fas fa-user",
        "orders.Order": "fas fa-box",
    },
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "emarket.middlewares.ForceEnglishAdminMiddleware",  # ← ضيفه هنا
]


# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "live.smtp.mailtrap.io"
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_USE_SSL = False
# EMAIL_HOST_USER = "api"
# EMAIL_HOST_PASSWORD = "7cbeca623e010c7a267b48bef02d39c6"


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "sandbox.smtp.mailtrap.io"
EMAIL_HOST_USER = "55df787a74bd5e"
EMAIL_HOST_PASSWORD = "00c71c3e07ba00"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = "test@example.com"

ROOT_URLCONF = "emarket.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "emarket.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "fragrance_db",
        "USER": "postgres",
        "PASSWORD": "Soft2022@postgre",
        "HOST": "localhost",
        "PORT": "5432",
    }
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    )
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
}
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "https://3sfragrance.com",
    "https://www.3sfragrance.com",
]

CORS_ALLOW_CREDENTIALS = True

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.AllowAny",),
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/


TIME_ZONE = "Africa/Cairo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_URL = "/static/"

STATIC_ROOT = os.path.join(BASE_DIR, "static")

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

SESSION_COOKIE_NAME = "sessionid"
SESSION_ENGINE = "django.contrib.sessions.backends.db"

# ✅ لأن الموقع بيشتغل على HTTPS
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# ✅ لازم None (علشان يسمح بالـ cross-subdomain cookies)
SESSION_COOKIE_SAMESITE = None
CSRF_COOKIE_SAMESITE = None

# ✅ خليك متأكد إنك بتسمح للفرونت إند بالتعامل مع السيرفر
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "https://3sfragrance.com",
    "https://www.3sfragrance.com",
]
CSRF_TRUSTED_ORIGINS = [
    "https://3sfragrance.com",
    "https://www.3sfragrance.com",
]
