# Generated by Django 5.2.1 on 2025-06-03 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True, max_length=1000)),
                ("price", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Speakers", "Speakers"),
                            ("Monitor Arm", "Monitorarm"),
                            ("Network", "Network"),
                            (
                                "Content Creation Accessories",
                                "Contentcreationaccessories",
                            ),
                            ("Computer Accessories", "Computeraccessories"),
                            ("Cameras", "Cameras"),
                            ("Mobile Accessories", "Mobileaccessories"),
                            ("Furniture", "Furniture"),
                            ("P.O.S. Service", "Posservice"),
                            ("Printing Paper", "Printingpaper"),
                        ],
                        max_length=40,
                    ),
                ),
                ("brand", models.CharField(max_length=50)),
                ("stock", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "addedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
