# Generated by Django 5.2.1 on 2025-06-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_product_slug_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
