# Generated by Django 5.2.1 on 2025-06-04 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("speakers", "Speakers"),
                    ("monitor arm", "Monitor Arm"),
                    ("network", "Network"),
                    ("content creation accessories", "Content Creation Accessories"),
                    ("computer accessories", "Computer Accessories"),
                    ("cameras", "Cameras"),
                    ("mobile accessories", "Mobile Accessories"),
                    ("furniture", "Furniture"),
                    ("P.O.S. Service", "P.O.S. Service"),
                    ("printing paper", "Printing Paper"),
                ],
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="product_images/")),
                ("alt_text", models.CharField(blank=True, max_length=100)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="product.product",
                    ),
                ),
            ],
        ),
    ]
