# Generated by Django 5.2.1 on 2025-07-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_product_discount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="description",
            new_name="description_en",
        ),
        migrations.RemoveField(
            model_name="product",
            name="name",
        ),
        migrations.AddField(
            model_name="product",
            name="description_ar",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="product",
            name="name_ar",
            field=models.CharField(default="بدون اسم", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="name_en",
            field=models.CharField(default="without name", max_length=200),
            preserve_default=False,
        ),
    ]
