# Generated by Django 5.2.1 on 2025-08-03 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_category_product_category_fk"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
    ]
