# Generated by Django 5.2.1 on 2025-08-03 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0009_alter_category_options_remove_product_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="category_fk",
            new_name="category",
        ),
    ]
