# Generated by Django 5.2.1 on 2025-08-10 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0010_rename_category_fk_product_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="name_en",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="description_en",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="name_en",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="product",
            name="description_ar",
        ),
        migrations.RemoveField(
            model_name="product",
            name="name_ar",
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size_ml", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=7)),
                ("stock", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="product.product",
                    ),
                ),
            ],
        ),
    ]
