# Generated by Django 5.2.1 on 2025-08-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0011_rename_name_en_category_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="name_ar",
        ),
        migrations.AddField(
            model_name="productvariant",
            name="discount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
