# Generated by Django 5.2.1 on 2025-08-10 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0012_remove_category_name_ar_productvariant_discount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
    ]
