# Generated by Django 5.2.1 on 2025-09-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0013_remove_product_discount_remove_product_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="travelsize",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="withbox",
            field=models.BooleanField(default=False),
        ),
    ]
