# Generated by Django 5.2.1 on 2025-10-02 23:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0014_productvariant_travelsize_productvariant_withbox"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productvariant",
            options={"ordering": ["size_ml"]},
        ),
    ]
