# Generated by Django 5.2.1 on 2025-10-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0015_alter_productvariant_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="category_images/"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="is_special",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="category",
            name="special_description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="special_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
