# Generated by Django 5.2.1 on 2025-10-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0016_category_image_category_is_special_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="short_description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
