# Generated by Django 5.2.1 on 2025-10-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0017_category_short_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfferImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="offers/slider/simple/", verbose_name="صورة العرض"
                    ),
                ),
            ],
            options={
                "verbose_name": "صورة عرض بسيطة",
                "verbose_name_plural": "صور العروض البسيطة",
                "ordering": ["id"],
            },
        ),
    ]
