# Generated by Django 5.2.1 on 2025-11-06 08:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0018_offerimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offerimage",
            options={"ordering": ["id"], "verbose_name_plural": "Offer Images"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-id"]},
        ),
    ]
