# Generated by Django 5.2.1 on 2025-12-05 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0019_alter_offerimage_options_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["priority", "-id"]},
        ),
        migrations.AddField(
            model_name="product",
            name="priority",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
