# Generated by Django 5.2.1 on 2026-01-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0020_alter_product_options_product_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="caption",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
