# Generated by Django 5.2.1 on 2026-02-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0021_productvariant_caption"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewsImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="reviews/slider/simple/", verbose_name="صورة التقييم"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Reviews Images",
                "ordering": ["id"],
            },
        ),
    ]
