# Generated by Django 5.2.1 on 2026-07-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0022_reviewsimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="allow_offer",
            field=models.BooleanField(default=True, verbose_name="يدخل في العروض"),
        ),
    ]
