# Generated by Django 5.2.1 on 2026-09-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0023_product_allow_offer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["order", "id"], "verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
