# Generated by Django 5.2.1 on 2025-11-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenttransaction",
            name="status",
            field=models.CharField(default="PENDING", max_length=100),
        ),
    ]
