# Generated by Django 5.2.1 on 2025-11-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_alter_paymenttransaction_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenttransaction",
            name="opay_reference",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
