# Generated by Django 5.2.1 on 2026-07-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "size_ml",
                    models.PositiveIntegerField(
                        choices=[(3, "3 ml"), (6, "6 ml"), (10, "10 ml"), (30, "30 ml")]
                    ),
                ),
                ("required_quantity", models.PositiveIntegerField()),
                ("gift_quantity", models.PositiveIntegerField(default=0)),
                ("original_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("offer_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("active", models.BooleanField(default=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
