# Generated by Django 5.2.1 on 2026-07-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="image",
            field=models.ImageField(
                default="", upload_to="offers/specials", verbose_name="صورة العرض"
            ),
            preserve_default=False,
        ),
    ]
