# Generated by Django 5.2.1 on 2026-07-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0002_offer_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="priority",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
