# Generated by Django 5.2.1 on 2025-10-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_remove_cartitem_product_cartitem_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="session_key",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
