# Generated by Django 5.2.1 on 2025-06-18 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("product", "0006_product_discount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_phone", models.CharField(max_length=20)),
                ("governorate", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("street", models.CharField(max_length=100)),
                (
                    "building_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "floor_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "apartment_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("landmark", models.CharField(blank=True, max_length=100, null=True)),
                ("total_amount", models.IntegerField(default=0)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("Paid", "Paid"), ("Unpaid", "Unpaid")],
                        default="Unpaid",
                        max_length=30,
                    ),
                ),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("Processing", "Processing"),
                            ("Shipped", "Shipped"),
                            ("Delivered", "Delivered"),
                        ],
                        default="Processing",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_phone", models.CharField(max_length=20)),
                ("name", models.CharField(default="", max_length=200)),
                ("quantity", models.IntegerField(default=1)),
                ("price", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orderitems",
                        to="order.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="product.product",
                    ),
                ),
            ],
        ),
    ]
