# Generated by Django 5.2.1 on 2025-06-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_remove_orderitem_customer_phone_alter_order_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=30.0, max_digits=10),
                ),
            ],
        ),
    ]
