# Generated by Django 5.2.1 on 2025-07-15 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_shippingsetting"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_phone", models.CharField(blank=True, max_length=20)),
                ("governorate", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("street", models.CharField(blank=True, max_length=255)),
                ("building_number", models.CharField(blank=True, max_length=10)),
                ("floor_number", models.CharField(blank=True, max_length=10)),
                ("apartment_number", models.CharField(blank=True, max_length=10)),
                ("landmark", models.CharField(blank=True, max_length=255)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "paymob_order_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
