# Generated by Django 5.2.1 on 2025-10-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0004_pendingorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingsetting",
            name="governorate",
            field=models.CharField(default="Cairo", max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shippingsetting",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=60.0, max_digits=10),
        ),
    ]
