# Generated by Django 5.2.1 on 2025-10-05 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0005_shippingsetting_governorate_and_more"),
        ("product", "0015_alter_productvariant_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="username",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="product.productvariant",
            ),
        ),
    ]
