# Generated by Django 5.2.1 on 2025-10-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0006_order_username_orderitem_variant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Unpaid", "غير مدفوع"),
                    ("Paid", "مدفوع"),
                    ("Shipping Paid", "تم دفع الشحن فقط"),
                ],
                default="Unpaid",
                max_length=30,
            ),
        ),
    ]
