# Generated by Django 5.2.1 on 2025-11-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0007_alter_order_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="username",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
