# Generated by Django 5.2.1 on 2025-11-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0008_alter_order_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="apartment_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="building_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="floor_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
