# Generated by Django 5.2.1 on 2025-11-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0009_alter_order_apartment_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="apartment_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="building_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="order",
            name="floor_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="landmark",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="street",
            field=models.CharField(max_length=255),
        ),
    ]
