# Generated by Django 5.2.1 on 2025-11-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0010_alter_order_apartment_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingorder",
            name="apartment_number",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="pendingorder",
            name="building_number",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="pendingorder",
            name="city",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="pendingorder",
            name="customer_phone",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="pendingorder",
            name="floor_number",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="pendingorder",
            name="governorate",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="pendingorder",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, max_digits=255),
        ),
    ]
