# Generated by Django 5.2.1 on 2025-11-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0011_alter_pendingorder_apartment_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="customer_phone",
            field=models.CharField(max_length=100),
        ),
    ]
