# Generated by Django 5.2.1 on 2025-11-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0012_alter_order_customer_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="opay_reference",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
