# Generated by Django 5.2.1 on 2025-12-05 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0013_order_opay_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Unpaid", "غير مدفوع"),
                    ("Paid", "مدفوع"),
                    ("Shipping Paid", "تم تاكيد الحجز"),
                ],
                default="Unpaid",
                max_length=30,
            ),
        ),
    ]
