# Generated by Django 5.2.1 on 2026-01-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0014_alter_order_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
