# Generated by Django 5.2.1 on 2026-07-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0015_order_shipping_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="applied_offers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
